# DLT Configuration Template for Facebook Pages Pipeline
# Copy this to .dlt/secrets.toml and fill in your actual values

facebook_refresh_token = "YOUR_FACEBOOK_LONG_LIVED_ACCESS_TOKEN_HERE"
facebook_page_id = "YOUR_FACEBOOK_PAGE_ID_HERE"
facebook_client_id = "YOUR_FACEBOOK_CLIENT_ID_HERE"
facebook_client_secret = "YOUR_FACEBOOK_CLIENT_SECRET_HERE"

# Optional: Adjust historical data range (days)
# days_back = 30

# How to get these values:
# 
# 1. Facebook Page ID:
#    - Go to your Facebook Page
#    - Click "About" tab
#    - Scroll down to "Page Info" section
#    - Your Page ID will be listed there
#    - OR: Use Facebook's Graph API Explorer: /{page-name}?fields=id
#
# 2. Long-lived Access Token:
#    - Use Facebook's Graph API Explorer: https://developers.facebook.com/tools/explorer/
#    - Select your App
#    - Get User Access Token with these permissions:
#      * pages_read_engagement
#      * pages_show_list  
#      * read_insights
#    - Convert short-lived token to long-lived using:
#      https://graph.facebook.com/oauth/access_token?grant_type=fb_exchange_token&client_id={app-id}&client_secret={app-secret}&fb_exchange_token={short-lived-token}
#
# Required Facebook App Permissions:
# - pages_read_engagement: Read engagement data from Pages
# - pages_show_list: List Pages the user manages
# - read_insights: Read insights and statistics from Pages
#
# Note: The access token should have at least 60 days validity for production use.